import sys
import os

# Add Miniconda site-packages BEFORE the script's directory so real packages win
_miniconda_site = r"C:\Users\Welcome\Miniconda3\Lib\site-packages"
if _miniconda_site not in sys.path:
    sys.path.insert(1, _miniconda_site)

# Remove script's parent dirs from path to prevent subdirectory shadowing
# (ai-intel/markdown/ and reports/markdown/ would shadow the real packages)
for _dir in [os.path.dirname(os.path.abspath(__file__)),
             os.path.dirname(os.path.abspath(__file__)).rsplit(os.sep, 1)[0]]:
    if _dir in sys.path:
        sys.path.remove(_dir)

import warnings as _warnings
_warnings.filterwarnings("ignore")

import markdown
from weasyprint import HTML, CSS

md_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_search_summary_2025-03-23.md"
css_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_report_style.css"
output_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_search_summary_2025-03-23.pdf"

with open(md_path, "r", encoding="utf-8") as f:
    md_content = f.read()

# Convert markdown to HTML with tables extension
html_body = markdown.markdown(
    md_content,
    extensions=['tables', 'fenced_code', 'toc']
)

# Wrap in full HTML document
html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Intelligence Report — March 23, 2026</title>
</head>
<body>
{html_body}
<footer>
    Report generated by OpenClaw AI Agent on March 23, 2026 · Sources: arXiv.org, Pluralsight, Mean CEO Blog, TileDB, Zapier, ByteByteGo, Nvidia Blog
</footer>
</body>
</html>"""

# Load external CSS
with open(css_path, "r", encoding="utf-8") as f:
    css_content = f.read()

css_obj = CSS(string=css_content)

# HTML(string=...) creates a document; .render() produces a printable object
html_obj = HTML(string=html_doc)
rendered = html_obj.render(stylesheets=[css_obj])
rendered.write_pdf(output_path)
print(f"PDF generated: {output_path}")
