import markdown
from weasyprint import HTML, CSS
import re

md_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_search_summary_2025-03-23.md"
css_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_report_style.css"
output_path = "C:/Users/Welcome/.openclaw/workspace/ai-intel/reports/ai_search_summary_2025-03-23.pdf"

with open(md_path, "r", encoding="utf-8") as f:
    md_content = f.read()

# Convert markdown to HTML with tables extension
html_body = markdown.markdown(
    md_content,
    extensions=['tables', 'fenced_code', 'toc']
)

# Wrap in full HTML document
html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Intelligence Report — March 23, 2026</title>
</head>
<body>
{html_body}
<footer class="report-footer">
    Report generated by OpenClaw AI Agent on March 23, 2026 · Sources: arXiv.org, Pluralsight, Mean CEO Blog, TileDB, Zapier, ByteByteGo, Nvidia Blog
</footer>
</body>
</html>"""

# Load external CSS
with open(css_path, "r", encoding="utf-8") as f:
    css_content = f.read()

css_obj = CSS(string=css_content)

html_obj.write_pdf(output_path, stylesheets=[css_obj])
print(f"PDF generated: {output_path}")
