import subprocess, os

os.chdir(r'C:\Users\Welcome\.openclaw\claw_store')

commands = [
    ['git', 'add', '-A'],
    ['git', 'commit', '-m', 'Add AI Intel reports for 2026-03-23\n\n- ai_search_summary: Google AI in Search 20-year digest\n- papers_daily: fresh ArXiv papers monitor\n\nGenerated by AI Intel monitoring system.'],
    ['git', 'push', 'store', 'main'],
]

for cmd in commands:
    print('Running:', ' '.join(cmd))
    r = subprocess.run(cmd, capture_output=True, text=True)
    print(r.stdout or '(no stdout)')
    if r.stderr:
        print('STDERR:', r.stderr[:300])
    print('Return code:', r.returncode, '\n')
